name: EC2 배포하기

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 올린 파일들 불러오기
        uses: actions/checkout@v4

      - name: JDK 21 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: application-secret.yml 파일 만들기
        run: |
          FILE="./src/main/resources/application-secret.yml"
          if [[ -f "$FILE" ]]; then
          rm -f -- "$FILE"
          fi
          : > "$FILE"
          echo "${{ secrets.APPLICATION_SECRET }}" > ./src/main/resources/application-secret.yml

      - name: 테스트 및 빌드
        run: ./gradlew clean build

      - name: 빌드된 jar 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/redis-prac/tobe

      - name: SSH로 ec2 접속
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            set -e
            rm -rf /home/ubuntu/redis-prac/current
            mkdir /home/ubuntu/redis-prac/current
            mv /home/ubuntu/redis-prac/tobe/project.jar /home/ubuntu/redis-prac/current/project.jar
            cd /home/ubuntu/redis-prac/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar project.jar > ./output.log 2>&1 &
            rm -rf /home/ubuntu/redis-prac/tobe